### ISSUE TITLE
Hello, requesting a csv file, validation and testing dataset.

### ISSUE THREAD

**Issue by johann83** [muzishen/Pet-ReID-IMAG#7]
Hello, 

it is great repository. I have a request for you. If you don't mind, could you please share full dataset, such that includes a csv file for training and validation dataset, also a dataset for validation and testing? If you do so, it will be a great help. 

Best regards

**Comment by drzraf** [comment]
Jumping on this too.
The dataset/weights mentioned in the README are paywalled/covered/restricted (hosted behind https://pan.baidu.com/)
![Screenshot from 2023-03-24 21-33-41](https://user-images.githubusercontent.com/1169926/227667807-1bd15368-9ad8-4196-84bf-6406588cdcc0.png)


![Screenshot from 2023-03-24 22-09-11](https://user-images.githubusercontent.com/1169926/227674439-dfa35f82-e97c-4303-87b6-d44e656e5671.png)


Could you please open this so that we can reproduce/confirm/reuse this amazing work effort?

Thank you!

**Comment by muzishen** [comment]
I have updated dataset. You can try it.

**Comment by drzraf** [comment]
![Screenshot from 2023-07-18 13-40-49](https://github.com/muzishen/Pet-ReID-IMAG/assets/1169926/57801405-9899-41e5-9f1b-4190fd62dca5)

Those who don't speak Chinese can't bypass the captcha (IIUC) :|

https://issuepcdn.baidupcs.com/issue/netdisk/yunguanjia/BaiduNetdisk_7.30.5.2.exe


The other link force the download of an `.exe` file instead of a `.zip`. Is Baidu the relevant platform when it comes to sharing files / dataset? Isn't there something more universal, simple and ubiquitous ?


![Screenshot from 2023-07-18 13-43-13](https://github.com/muzishen/Pet-ReID-IMAG/assets/1169926/3bc85a2f-c725-46de-93dd-44d3d76e37f0)

**Comment by muzishen** [comment]
> 

Sorry, we have update link in google drive, i.e.,  https://drive.google.com/drive/folders/1_7pdSRTvD_XdTu8z0MxrM9PDoEuX-tjf?usp=sharing

**Comment by johann83** [comment]
I downloaded it. Thank you for your help!!!
